# Generated by Django 2.2.1 on 2019-05-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_author', models.CharField(max_length=100)),
                ('quote_body', models.TextField()),
                ('context', models.CharField(blank=True, max_length=240)),
                ('source', models.URLField(blank=True, max_length=130)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
